### ISSUE TITLE
Crash on 1.10 during client load

### ISSUE THREAD

**Issue by t3f** [jaquadro/Chameleon#2]
Getting a crash with v. 2.1.6 on Forge 1.10.2-12.18.1.2014 during client load screen. 

Gist https://gist.github.com/t3f/4f9716daa100468c73ad7132124ec1f2

**Comment by t3f** [comment]
Seems to only occur with SD 3.2.0 & 3.2.1, the older 3.1.11 works.

StorageDrawers-1.9.4-3.2.1.jar
StorageDrawers-1.9.4-3.2.0.jar

**Comment by jaquadro** [comment]
Are you sure you're using 2.1.6?  Your stack trace does not correspond with that version .. looks like it's probably 2.1.5.

**Comment by t3f** [comment]
Oof, you are right, I was only getting the error with 2.1.5 and 3.2.*.  Sorry about that.
